### ISSUE TITLE
Documentation for the module 

### ISSUE THREAD

**Issue by robin025** [codezonediitj/pydatastructs#338] opened 2021-03-08 16:38 UTC
hey I am a GSSoC 21 Participant and would like to contribute to this python module

#### Description of the problem
So I was scrolling down to the code base and I found that when a new user installs this module then it will be hard for the user to import different algorithms and data-structures without documentation, so I would like to create the docs for this module using Sphinx(so sphinx is used to generating docs easily with the help of restructured text or .rst), so when I was scrolling through the programs, I found that docstrings are used which I think is good for understanding the concepts of that algorithms or data-structures, but sometimes it becomes annoying to open a .py file to read all the working and examples of that algorithms but with the help of docstrings like in [this](https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/linear_data_structures/algorithms.py) case, so we can make use of .rst fill to generate auto docs using sphinx on the ReadTheDocs website and the main thing is, it is completely free

#### References/Other comments
So I have also created a similar module like this with docs too with the help of the ReadTheDocs website but I don't think so that 
my module can reach many developers so that's why I chose your module to start the open-source journey
[this](https://pythorn.readthedocs.io/en/latest/) is the link where you can read the docs of my module

**I Would Like To Work On This Issue**

looking forward to your reply
thanks

**Comment by Ananya88** [comment] 2021-03-09 09:52
Hey !!
I am interested in this project as GSSOC '21 participant .
And I would like to to update the Readme.md file by adding by making it more beginner and intermediate friendly by adding links to learn python and DSA in python.

Please assign me with this issue .Thanks.

**Comment by nNikita1018** [comment] 2021-03-09 15:33
I want work with this project by solving this issue.

**Comment by czgdp1807** [comment] 2021-03-11 05:02
Duplicate of https://github.com/codezonediitj/pydatastructs/issues/7
Please comment there. This is a very long term issue. I have no problem if someone works on but it may take a bit of time and effort to actually make documentation work. We will upload the html code on readthedocs.io

**Closed** 2021-03-11 05:03 UTC
Labels: duplicate
