### ISSUE TITLE
Add M-ary Tree

### ISSUE THREAD

**Issue by Saptashrungi** [codezonediitj/pydatastructs#170] opened 2020-03-18 10:02 UTC
#### References/Other comments
https://en.wikipedia.org/wiki/M-ary_tree#Types_of_m-ary_trees

**Comment by Saptashrungi** [comment] 2020-03-18 10:03
I would like to work on this issue.

**Comment by czgdp1807** [comment] 2020-03-18 10:05
Closing. Duplicate of #101

**Closed** 2020-03-18 10:05 UTC
